# Automatically generated from verified RED .118 stock.
# Android 15 contract: source-owned HAL wrappers, stale stock init, and factory/debug payload are pruned.

PRODUCT_SOONG_NAMESPACES += \
    vendor/red/hydrogenone

PRODUCT_COPY_FILES += \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800h_8998_660.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h_8998_660.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800s_dsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800s_dsp.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/hw/init.msm.usb.configfs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.msm.usb.configfs.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.cm.hardware.thermal3d@1.0-service.cm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.cm.hardware.thermal3d@1.0-service.cm.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.leia.hardware.leiadisp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.leia.hardware.leiadisp@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.rild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp-NQ3XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-NQ3XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp-NQ4XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-NQ4XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_rf1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_rf1.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_rf2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_rf2.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nci_NCI2_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_NCI2_0.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nxp_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd-NQ3XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-NQ3XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd-NQ4XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-NQ4XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_rf1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_rf1.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_rf2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_rf2.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/permissions/android.hardware.nfc.hcef.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.nfc.hcef.xml \
    vendor/red/hydrogenone/proprietary/vendor/etc/permissions/com.android.nfc_extras.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.android.nfc_extras.xml \
    vendor/red/hydrogenone/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/thermal-engine-3d.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-3d.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/red/hydrogenone/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw

PRODUCT_PACKAGES += \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.uceservice@2.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    audio.primary.default \
    com.qualcomm.qti.bluetooth_audio@1.0-impl \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    nfc_nci.nqx.default \
    vendor.qti.esepowermanager@1.0-impl \
    vendor.qti.gnss@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsxml \
    lib-siputility \
    libC2D2 \
    libCB \
    libDRPlugin \
    libOpenCL \
    libQSEEComAPI \
    libadreno_utils \
    libadsprpc \
    libaudio_log_utils \
    libc2d30_bltlib \
    libconfigdb \
    libdataitems \
    libdiag \
    libdrplugin_client \
    libdsi_netctrl \
    libdsutils \
    libevent_observer \
    libflp \
    libgeofence \
    libgsl \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    libmdmdetect \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libnetmgr \
    libperipheral_client \
    libqcrilFramework \
    libqdi \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_encdec \
    libqmiservices \
    libqservice \
    libril-qcril-hook-oem \
    libril \
    librilutils \
    librpmb \
    libsdm-disp-apis \
    libsdm-disp-vndapis \
    libsdmutils \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsettings \
    libsns_low_lat_stream_stub \
    libthermalclient \
    libtime_genoff \
    libtinycompress_vendor \
    libulp2 \
    libxml \
    libxtadapter \
    nfc_nci.nqx.default.hw \
    qcrild_librilutils \
    sensors.ssc \
    vendor.cm.hardware.thermal3d@1.0 \
    vendor.display.color@1.0 \
    vendor.leia.hardware.leiadisp@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    com.qualcomm.qti.wifidisplayhal@1.0-halimpl \
    com.qualcomm.qti.wifidisplayhal@1.0 \
    camera.msm8998 \
    libSonyIMX380PdafLibrary \
    libactuator_lc898219xl_main \
    libactuator_lc898219xl_sub \
    libarcsoft_antishaking \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_shot \
    libavservices_minijail_vendor \
    libchromatix_imx268_main_1080p_3d_video_lc898122 \
    libchromatix_imx268_main_1080p_hfr_60 \
    libchromatix_imx268_main_1080p_hfr_60_lc898122 \
    libchromatix_imx268_main_360p_3d_video_lc898122 \
    libchromatix_imx268_main_480p_hfr_60 \
    libchromatix_imx268_main_480p_hfr_60_lc898122 \
    libchromatix_imx268_main_720p_hfr_60 \
    libchromatix_imx268_main_720p_hfr_60_lc898122 \
    libchromatix_imx268_main_common \
    libchromatix_imx268_main_cpp_1080p_hfr_60 \
    libchromatix_imx268_main_cpp_480p_hfr_60 \
    libchromatix_imx268_main_cpp_720p_hfr_60 \
    libchromatix_imx268_main_cpp_liveshot \
    libchromatix_imx268_main_cpp_preview \
    libchromatix_imx268_main_cpp_snapshot \
    libchromatix_imx268_main_cpp_snapshot_arc_hdr \
    libchromatix_imx268_main_cpp_snapshot_bokeh \
    libchromatix_imx268_main_cpp_snapshot_eis \
    libchromatix_imx268_main_cpp_snapshot_lls \
    libchromatix_imx268_main_cpp_video \
    libchromatix_imx268_main_default_video \
    libchromatix_imx268_main_postproc \
    libchromatix_imx268_main_preview \
    libchromatix_imx268_main_snapshot \
    libchromatix_imx268_main_snapshot_bokeh \
    libchromatix_imx268_main_zsl_preview_lc898122 \
    libchromatix_imx268_main_zsl_preview_lc898122_3dmode \
    libchromatix_imx268_main_zsl_preview_lc898122_bokeh \
    libchromatix_imx268_main_zsl_video_lc898122 \
    libchromatix_imx268_sub_1080p_3d_video_lc898122 \
    libchromatix_imx268_sub_1080p_hfr_60 \
    libchromatix_imx268_sub_1080p_hfr_60_lc898122 \
    libchromatix_imx268_sub_360p_3d_video_lc898122 \
    libchromatix_imx268_sub_480p_hfr_60 \
    libchromatix_imx268_sub_480p_hfr_60_lc898122 \
    libchromatix_imx268_sub_720p_hfr_60 \
    libchromatix_imx268_sub_720p_hfr_60_lc898122 \
    libchromatix_imx268_sub_common \
    libchromatix_imx268_sub_cpp_1080p_hfr_60 \
    libchromatix_imx268_sub_cpp_480p_hfr_60 \
    libchromatix_imx268_sub_cpp_720p_hfr_60 \
    libchromatix_imx268_sub_cpp_liveshot \
    libchromatix_imx268_sub_cpp_preview \
    libchromatix_imx268_sub_cpp_snapshot \
    libchromatix_imx268_sub_cpp_snapshot_arc_hdr \
    libchromatix_imx268_sub_cpp_snapshot_bokeh \
    libchromatix_imx268_sub_cpp_snapshot_eis \
    libchromatix_imx268_sub_cpp_snapshot_lls \
    libchromatix_imx268_sub_cpp_video \
    libchromatix_imx268_sub_default_video \
    libchromatix_imx268_sub_postproc \
    libchromatix_imx268_sub_preview \
    libchromatix_imx268_sub_snapshot \
    libchromatix_imx268_sub_snapshot_bokeh \
    libchromatix_imx268_sub_zsl_preview_lc898122 \
    libchromatix_imx268_sub_zsl_preview_lc898122_3dmode \
    libchromatix_imx268_sub_zsl_preview_lc898122_bokeh \
    libchromatix_imx268_sub_zsl_video_lc898122 \
    libchromatix_imx380_main_1080p_3d_video_lc898122 \
    libchromatix_imx380_main_1080p_hfr_60 \
    libchromatix_imx380_main_1080p_hfr_60_lc898122 \
    libchromatix_imx380_main_360p_3d_video_lc898122 \
    libchromatix_imx380_main_480p_hfr_240 \
    libchromatix_imx380_main_480p_hfr_240_lc898122 \
    libchromatix_imx380_main_4k_3d_snapshot_lc898122 \
    libchromatix_imx380_main_4k_panorama_lc898122 \
    libchromatix_imx380_main_4k_preview_lc898122 \
    libchromatix_imx380_main_4k_video_lc898122 \
    libchromatix_imx380_main_720p_hfr_120 \
    libchromatix_imx380_main_720p_hfr_120_lc898122 \
    libchromatix_imx380_main_common \
    libchromatix_imx380_main_cpp_1080p_3d_video \
    libchromatix_imx380_main_cpp_1080p_hfr_60 \
    libchromatix_imx380_main_cpp_480p_hfr_240 \
    libchromatix_imx380_main_cpp_4k_3d_snapshot \
    libchromatix_imx380_main_cpp_720p_hfr_120 \
    libchromatix_imx380_main_cpp_liveshot \
    libchromatix_imx380_main_cpp_preview \
    libchromatix_imx380_main_cpp_qhd_hfr_60 \
    libchromatix_imx380_main_cpp_snapshot \
    libchromatix_imx380_main_cpp_snapshot_arc_hdr \
    libchromatix_imx380_main_cpp_snapshot_bokeh \
    libchromatix_imx380_main_cpp_snapshot_eis \
    libchromatix_imx380_main_cpp_snapshot_flash \
    libchromatix_imx380_main_cpp_snapshot_hdr \
    libchromatix_imx380_main_cpp_snapshot_lls \
    libchromatix_imx380_main_cpp_video \
    libchromatix_imx380_main_default_video \
    libchromatix_imx380_main_postproc \
    libchromatix_imx380_main_preview \
    libchromatix_imx380_main_qhd_hfr_60 \
    libchromatix_imx380_main_qhd_hfr_60_lc898122 \
    libchromatix_imx380_main_snapshot \
    libchromatix_imx380_main_snapshot_bokeh \
    libchromatix_imx380_main_zsl_preview_lc898122 \
    libchromatix_imx380_main_zsl_preview_lc898122_3dmode \
    libchromatix_imx380_main_zsl_preview_lc898122_bokeh \
    libchromatix_imx380_main_zsl_video_lc898122 \
    libchromatix_imx380_sub_1080p_3d_video_lc898122 \
    libchromatix_imx380_sub_1080p_hfr_60 \
    libchromatix_imx380_sub_1080p_hfr_60_lc898122 \
    libchromatix_imx380_sub_360p_3d_video_lc898122 \
    libchromatix_imx380_sub_480p_hfr_240 \
    libchromatix_imx380_sub_480p_hfr_240_lc898122 \
    libchromatix_imx380_sub_4k_3d_snapshot_lc898122 \
    libchromatix_imx380_sub_4k_panorama_lc898122 \
    libchromatix_imx380_sub_4k_preview_lc898122 \
    libchromatix_imx380_sub_4k_video_lc898122 \
    libchromatix_imx380_sub_720p_hfr_120 \
    libchromatix_imx380_sub_720p_hfr_120_lc898122 \
    libchromatix_imx380_sub_common \
    libchromatix_imx380_sub_cpp_1080p_3d_video \
    libchromatix_imx380_sub_cpp_1080p_hfr_60 \
    libchromatix_imx380_sub_cpp_480p_hfr_240 \
    libchromatix_imx380_sub_cpp_4k_3d_snapshot \
    libchromatix_imx380_sub_cpp_720p_hfr_120 \
    libchromatix_imx380_sub_cpp_liveshot \
    libchromatix_imx380_sub_cpp_preview \
    libchromatix_imx380_sub_cpp_qhd_hfr_60 \
    libchromatix_imx380_sub_cpp_snapshot \
    libchromatix_imx380_sub_cpp_snapshot_arc_hdr \
    libchromatix_imx380_sub_cpp_snapshot_bokeh \
    libchromatix_imx380_sub_cpp_snapshot_eis \
    libchromatix_imx380_sub_cpp_snapshot_flash \
    libchromatix_imx380_sub_cpp_snapshot_hdr \
    libchromatix_imx380_sub_cpp_snapshot_lls \
    libchromatix_imx380_sub_cpp_video \
    libchromatix_imx380_sub_default_video \
    libchromatix_imx380_sub_postproc \
    libchromatix_imx380_sub_preview \
    libchromatix_imx380_sub_qhd_hfr_60 \
    libchromatix_imx380_sub_qhd_hfr_60_lc898122 \
    libchromatix_imx380_sub_snapshot \
    libchromatix_imx380_sub_snapshot_bokeh \
    libchromatix_imx380_sub_zsl_preview_lc898122 \
    libchromatix_imx380_sub_zsl_preview_lc898122_3dmode \
    libchromatix_imx380_sub_zsl_preview_lc898122_bokeh \
    libchromatix_imx380_sub_zsl_video_lc898122 \
    libdepthmapwrapper \
    libfastcvopt \
    libflash_pmic \
    libhal_dbg \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_arcsoftlls \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_blackwhite \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_gt24p64b_main_eeprom \
    libmmcamera_gt24p64b_sub_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hdrgreyscale \
    libmmcamera_highcontrast \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx214 \
    libmmcamera_imx230 \
    libmmcamera_imx258 \
    libmmcamera_imx258_gt24c16_eeprom \
    libmmcamera_imx258_gt24c32_eeprom \
    libmmcamera_imx258_mono \
    libmmcamera_imx258_mono_gt24c32_eeprom \
    libmmcamera_imx268_main \
    libmmcamera_imx268_sub \
    libmmcamera_imx298 \
    libmmcamera_imx318 \
    libmmcamera_imx362 \
    libmmcamera_imx362_gt24c64a \
    libmmcamera_imx376 \
    libmmcamera_imx378 \
    libmmcamera_imx380_main \
    libmmcamera_imx380_sub \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_m24c64s_main_eeprom \
    libmmcamera_m24c64s_sub_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_thread_services \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmosal_proprietary \
    libmpbase \
    libqdMetaData \
    libqomx_core \
    libremosaic_daemon \
    libwfdcommonutils_proprietary \
    libwfdhaldsmanager \
    libwfdhdcpcp \
    libwfdmmservice \
    libwfdmodulehdcpsession \
    com.fingerprints.extension@1.0 \
    com.qualcomm.qti.ant@1.0 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    com.quicinc.cne.server@2.0 \
    com.quicinc.cne.server@2.1 \
    com.quicinc.cne.server@2.2 \
    com.quicinc.cne.server@2.3 \
    android.hardware.keymaster@3.0-impl-qti \
    vendor.cm.hardware.thermal3d@1.0-impl \
    vendor.leia.hardware.leiadisp@1.0-impl \
    vulkan.msm8998 \
    lib-dplmedia \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    libFlacSwDec \
    libOmxAacDec \
    libOmxAacEnc \
    libOmxAmrDec \
    libOmxAmrEnc \
    libOmxAmrwbplusDec \
    libOmxEvrcEnc \
    libOmxQcelp13Enc \
    libOmxWmaDec \
    libadsp_default_listener \
    libaudioalsa \
    libbtnv \
    libcneapiclient \
    libdrmfs \
    libdrmutils \
    libgdtap \
    libgpustats \
    libhdr_tm \
    libjson \
    libkeymasterdeviceutils \
    liblowi_wifihal \
    liblqe \
    libmm-omxcore \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libnetmgr_common \
    libnlnetmgr \
    libpdmapper \
    libpdnotifier \
    libqcci_legacy \
    libqdp \
    libqmi_csi \
    libqrtr \
    libqseed3 \
    libqsocket \
    libril-qc-hal-qmi \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    librilqmiservices \
    librmnetctl \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdmextension \
    libspcom \
    libssd \
    libsystem_health_mon \
    libthermalioctl \
    libtinyxml2_1 \
    libxtwifi_ulp_adaptor \
    vendor.nxp.hardware.nfc@1.0 \
    vendor.qti.data.factory@1.0 \
    vendor.qti.data.factory@1.1 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.imsrtpservice@1.0-service-Impl \
    vendor.qti.imsrtpservice@1.0 \
    vendor.qti.latency@2.0 \
    adsprpcd \
    energy-awareness \
    hvdcp_opti \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    qcrild \
    rild \
    vendor.cm.hardware.thermal3d@1.0-service.cm \
    vendor.leia.hardware.leiadisp@1.0-service \
    vendor.qti.esepowermanager@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    netmgrd \
    nqnfcinfo \
    pd-mapper \
    pm-proxy \
    pm-service \
    qseecomd \
    rmt_storage \
    sensors.qti \
    spdaemon \
    tftp_server \
    thermal-engine \
    wcnss_filter \
    wifidisplayhalservice \
    xtwifi-client \
    xtwifi-inet-agent

PRODUCT_COPY_FILES += \
    vendor/red/hydrogenone/proprietary/vendor/bin/init.qcom.sensors.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.sensors.sh \
    vendor/red/hydrogenone/proprietary/vendor/bin/init.qti.ims.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qti.ims.sh

# LineageOS 22.2 source-owned replacements for pruned RED .118 prebuilts
PRODUCT_PACKAGES += \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    libaudiopreprocessing \
    libcld80211 \
    libgps.utils \
    libhidlbase_shim \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    libloc_core \
    liblocation_api \
    libwifi-hal \
    vendor.qti.hardware.camera.device@1.0
