# Automatically generated from verified RED .118 stock.
# Android 15 contract: source-owned HAL wrappers, stale stock init, and factory/debug payload are pruned.

PRODUCT_SOONG_NAMESPACES += \
    vendor/red/hydrogenone

PRODUCT_COPY_FILES += \
    vendor/red/hydrogenone/proprietary/vendor/bin/init.qcom.sensors.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.sensors.sh \
    vendor/red/hydrogenone/proprietary/vendor/bin/init.qti.ims.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qti.ims.sh \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800h_8998_660.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h_8998_660.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/hbtp/qtc800s_dsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800s_dsp.bin \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/hw/init.msm.usb.configfs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.msm.usb.configfs.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.cm.hardware.thermal3d@1.0-service.cm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.cm.hardware.thermal3d@1.0-service.cm.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.leia.hardware.leiadisp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.leia.hardware.leiadisp@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.0-service.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/init/vendor.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.rild.rc \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp-NQ3XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-NQ3XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp-NQ4XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-NQ4XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_rf1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_rf1.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-mtp_rf2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp_rf2.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nci_NCI2_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_NCI2_0.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-nxp_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd-NQ3XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-NQ3XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd-NQ4XX.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-NQ4XX.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_default.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_rf1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_rf1.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/libnfc-qrd_rf2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd_rf2.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/permissions/android.hardware.nfc.hcef.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.nfc.hcef.xml \
    vendor/red/hydrogenone/proprietary/vendor/etc/permissions/com.android.nfc_extras.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.android.nfc_extras.xml \
    vendor/red/hydrogenone/proprietary/vendor/etc/thermal-engine-3d.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-3d.conf \
    vendor/red/hydrogenone/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/red/hydrogenone/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/red/hydrogenone/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/red/hydrogenone/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw

PRODUCT_PACKAGES += \
    adsprpcd \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.media.omx@1.0-service \
    audio.primary.default \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.msm8998 \
    vendor.qti.hardware.camera.device@1.0 \
    com.fingerprints.extension@1.0 \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0-impl \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.wifidisplayhal@1.0 \
    com.qualcomm.qti.wifidisplayhal@1.0-halimpl \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    com.quicinc.cne.server@2.0 \
    com.quicinc.cne.server@2.1 \
    com.quicinc.cne.server@2.2 \
    com.quicinc.cne.server@2.3 \
    eglSubDriverAndroid \
    gatekeeper.msm8998 \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    keystore.msm8998 \
    lib-dplmedia \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsxml \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    lib-siputility \
    libC2D2 \
    libCB \
    libDRPlugin \
    libEGL_adreno \
    libFlacSwDec \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libOmxAacDec \
    libOmxAacEnc \
    libOmxAmrDec \
    libOmxAmrEnc \
    libOmxAmrwbplusDec \
    libOmxEvrcEnc \
    libOmxQcelp13Enc \
    libOmxWmaDec \
    libOpenCL \
    libQSEEComAPI \
    libQTapGLES \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libarcsoft_antishaking \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_shot \
    libaudio_log_utils \
    libaudioalsa \
    libaudiopreprocessing \
    libavservices_minijail_vendor \
    libbtnv \
    libc2d30_bltlib \
    libcld80211 \
    libcneapiclient \
    libconfigdb \
    libdataitems \
    libdepthmapwrapper \
    libdiag \
    libdrmfs \
    libdrmutils \
    libdrplugin_client \
    libdsi_netctrl \
    libdsutils \
    libevent_observer \
    libfastcvopt \
    libflp \
    libgdtap \
    libgeofence \
    libgps.utils \
    libgpustats \
    libgsl \
    libgui_vendor \
    libhal_dbg \
    libhdr_tm \
    libidl \
    libizat_client_api \
    libizat_core \
    libjson \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    liblbs_core \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libmm-omxcore \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_arcsoftlls \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_blackwhite \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_gt24p64b_main_eeprom \
    libmmcamera_gt24p64b_sub_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hdrgreyscale \
    libmmcamera_highcontrast \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx214 \
    libmmcamera_imx230 \
    libmmcamera_imx258 \
    libmmcamera_imx258_gt24c16_eeprom \
    libmmcamera_imx258_gt24c32_eeprom \
    libmmcamera_imx258_mono \
    libmmcamera_imx258_mono_gt24c32_eeprom \
    libmmcamera_imx268_main \
    libmmcamera_imx268_sub \
    libmmcamera_imx298 \
    libmmcamera_imx318 \
    libmmcamera_imx362 \
    libmmcamera_imx362_gt24c64a \
    libmmcamera_imx376 \
    libmmcamera_imx378 \
    libmmcamera_imx380_main \
    libmmcamera_imx380_sub \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_sub_module \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmosal_proprietary \
    libmpbase \
    libnbaio_mono \
    libnetmgr \
    libnetmgr_common \
    libnlnetmgr \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libq3dtools_adreno \
    libq3dtools_esx \
    libqcci_legacy \
    libqcrilFramework \
    libqdMetaData \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqomx_core \
    libqseed3 \
    libqservice \
    libril \
    libril-qc-hal-qmi \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librilutils \
    librmnetctl \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-apis \
    vendor.display.color@1.0 \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdmutils \
    libsensor1 \
    libsettings \
    libstagefright_foundation-v28 \
    libstagefright_omx-v28 \
    libsystem_health_mon \
    libthermalclient \
    libthermalioctl \
    libtime_genoff \
    libtinycompress_vendor \
    libtinyxml2_1 \
    libulp2 \
    libwebrtc_audio_preprocessing \
    libwfdcommonutils_proprietary \
    libwfdhaldsmanager \
    libwfdhdcpcp \
    libwfdmmservice \
    libwfdmodulehdcpsession \
    libwifi-hal \
    libxml \
    libxtadapter \
    libxtwifi_ulp_adaptor \
    netmgrd \
    nfc_nci.nqx.default \
    nfc_nci.nqx.default.hw \
    nqnfcinfo \
    pd-mapper \
    pm-proxy \
    pm-service \
    qcrild \
    qcrild_librilutils \
    qseecomd \
    rild \
    rmt_storage \
    sensors.qti \
    thermal-engine \
    vendor.cm.hardware.thermal3d@1.0 \
    vendor.cm.hardware.thermal3d@1.0-impl \
    vendor.cm.hardware.thermal3d@1.0-service.cm \
    vendor.leia.hardware.leiadisp@1.0 \
    vendor.leia.hardware.leiadisp@1.0-impl \
    vendor.leia.hardware.leiadisp@1.0-service \
    vendor.nxp.hardware.nfc@1.0 \
    vendor.qti.data.factory@1.0 \
    vendor.qti.data.factory@1.1 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.0-impl \
    vendor.qti.esepowermanager@1.0-service \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.0-impl \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.imsrtpservice@1.0 \
    vendor.qti.imsrtpservice@1.0-service-Impl \
    vendor.qti.latency@2.0 \
    vulkan.msm8998 \
    wcnss_filter \
    wifidisplayhalservice \
    xtwifi-client \
    xtwifi-inet-agent

# RED .118 P0 daemon completion
PRODUCT_PACKAGES += \
    energy-awareness \
    hvdcp_opti \
    libspcom \
    spdaemon

# Android 15 compatibility for RED Android 9 HIDL prebuilts
PRODUCT_PACKAGES += \
    libhidlbase_shim
